# Generated by Django 3.2.3 on 2021-06-06 14:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Accounts', '0004_profile_age'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='gender',
            field=models.CharField(choices=[('MA', 'Male'), ('FE', 'Female'), ('OT', 'Other')], default='MA', max_length=2),
        ),
    ]
