# Generated by Django 3.2.3 on 2021-06-14 13:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Accounts', '0006_profile_follower'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='following',
            field=models.IntegerField(default=0),
        ),
    ]
