# Generated by Django 3.2.3 on 2021-06-18 12:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Accounts', '0008_auto_20210618_0552'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='friends',
            new_name='follower',
        ),
    ]
