# Generated by Django 4.0.2 on 2022-07-09 08:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Accounts', '0010_alter_profile_options'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='gender',
        ),
    ]
